					<section class="animate-in fade-in duration-300">
						<div class="border-border bg-card rounded-lg border">
							<div class="border-border border-b px-6 py-4">
								<h2 class="text-foreground text-xl font-semibold">Technical Details</h2>
							</div>
							<div class="px-6 py-6">
								<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
									<div>
										<h3 class="text-foreground mb-3 font-semibold">Architecture</h3>
										<div class="text-foreground space-y-2 text-sm">
											<p>
												<strong class="text-foreground">Framework:</strong> SvelteKit 2 with Svelte 5
											</p>
											<p>
												<strong class="text-foreground">Language:</strong> TypeScript with strict typing
											</p>
											<p><strong class="text-foreground">Styling:</strong> Tailwind CSS 4</p>
											<p>
												<strong class="text-foreground">State:</strong> Svelte 5 runes-based stores
											</p>
											<p><strong class="text-foreground">Validation:</strong> Zod schemas</p>
										</div>
									</div>

									<div>
										<h3 class="text-foreground mb-3 font-semibold">Processing</h3>
										<div class="text-foreground space-y-2 text-sm">
											<p>
												<strong class="text-foreground">Engine:</strong> Canvas API with Web Workers
											</p>
											<p>
												<strong class="text-foreground">Storage:</strong> IndexedDB + ZIP export
											</p>
											<p>
												<strong class="text-foreground">Caching:</strong> LRU with ObjectURL management
											</p>
											<p><strong class="text-foreground">Images:</strong> Up to 4096x4096px</p>
											<p>
												<strong class="text-foreground">Formats:</strong> PNG, JPG, GIF, WebP, SVG
											</p>
										</div>
									</div>
								</div>

								<div class="bg-muted mt-6 rounded-lg p-4">
									<h4 class="text-foreground mb-2 font-semibold">
										Metadata Structure
									</h4>
									<pre
										class="bg-card text-foreground overflow-x-auto rounded border p-3 text-xs">{`{
  "name": "Collection #1",
  "description": "Generated by GNStudio",
  "image": "images/1.png",
  "edition": 1,
  "attributes": [
    {"trait_type": "Background", "value": "Blue"},
    {"trait_type": "Character", "value": "Robot"}
  ]
}`}</pre>
								</div>
							</div>
						</div>
					</section>
