<script lang="ts">
</script>

					<section class="animate-in fade-in duration-300">
						<div class="border-border bg-card rounded-lg border">
							<div class="border-border border-b px-6 py-4">
								<h2 class="text-foreground text-xl font-semibold">Gallery Mode</h2>
							</div>
							<div class="px-6 py-6">
								<div class="space-y-8">
									<div>
										<h3 class="text-foreground mb-4 font-semibold">View & Manage Collections</h3>
										<p class="text-muted-foreground mb-4">
											Gallery Mode provides a powerful interface for viewing, filtering, and
											managing your generated collections. Access it by clicking "Gallery Mode"
											in the top-right corner of the main app.
										</p>

										<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
											<div>
												<h4 class="text-foreground mb-3 font-semibold">Collection Management</h4>
												<div class="text-muted-foreground space-y-2 text-sm">
													<p>• Import existing collections from ZIP files</p>
													<p>• View multiple collections in one interface</p>
													<p>• Automatic metadata parsing and organization</p>
													<p>• Collection statistics and insights</p>
												</div>
											</div>
												<div>
													<h4 class="text-foreground mb-3 font-semibold">Advanced Filtering</h4>
													<div class="text-muted-foreground space-y-2 text-sm">
														<p>• Search by item name and description</p>
														<p>• Multi-layer trait filtering</p>
														<p>• Sort by rarity or natural item name</p>
														<p>• Real-time filter results</p>
													</div>
											</div>
										</div>
									</div>

									<div>
										<h3 class="text-foreground mb-4 font-semibold">Interactive Trait Filtering</h3>
										<p class="text-muted-foreground mb-4">
											Click on any trait in item details to instantly filter the entire collection by
											that trait. Build complex filters by selecting multiple traits from different
											layers.
										</p>

										<div class="border-border bg-muted rounded-lg border p-4">
											<h4 class="text-foreground mb-2 font-semibold">
												How Interactive Filtering Works:
											</h4>
											<ul class="text-muted-foreground ml-4 list-disc space-y-1 text-sm">
												<li>Click any item to view its details in the right panel</li>
												<li>Click on individual traits to filter by that specific attribute</li>
												<li>Selected traits are highlighted with primary color styling</li>
												<li>Build multi-trait filters by clicking additional traits</li>
												<li>Use "Clear All" to reset all active filters</li>
											</ul>
										</div>
									</div>

									<div>
										<h3 class="text-foreground mb-4 font-semibold">Responsive Design</h3>
										<p class="text-muted-foreground mb-4">
											Gallery Mode is optimized for all devices with adaptive layouts that provide
											the best experience on mobile, tablet, and desktop.
										</p>

										<div class="grid grid-cols-1 gap-4 md:grid-cols-3">
											<div class="border-border bg-muted rounded-lg border p-4">
												<h4 class="text-foreground mb-2 font-semibold">Mobile</h4>
												<p class="text-muted-foreground text-sm">
													Full-width grid layout with bottom details panel and horizontal scrolling
													traits
												</p>
											</div>
											<div class="border-border bg-muted rounded-lg border p-4">
												<h4 class="text-foreground mb-2 font-semibold">Tablet</h4>
												<p class="text-muted-foreground text-sm">
													Balanced layout with optimized grid sizing and responsive trait filters
												</p>
											</div>
											<div class="border-border bg-muted rounded-lg border p-4">
												<h4 class="text-foreground mb-2 font-semibold">Desktop</h4>
												<p class="text-muted-foreground text-sm">
													70/30 split layout with fixed right panel and comprehensive item details
												</p>
											</div>
										</div>
									</div>

									<div>
										<h3 class="text-foreground mb-4 font-semibold">Import Collections</h3>
										<p class="text-muted-foreground mb-4">
											Seamlessly import collections generated by other tools or external platforms
											into Gallery Mode for viewing and filtering.
										</p>

										<div class="border-border bg-muted rounded-lg border p-4">
													<h4 class="text-foreground mb-2 font-semibold">Supported Import Features:</h4>
												<ul class="text-muted-foreground ml-4 list-disc space-y-1 text-sm">
													<li>ZIP files with images/ and metadata/ folder structure</li>
													<li>PNG, JPG, WebP, and GIF image entries</li>
													<li>Automatic metadata parsing and organization</li>
													<li>Automatic rarity calculation and ranking system</li>
													<li>Support for various metadata formats and trait structures</li>
													<li>Duplicate collection name handling with automatic numbering</li>
													<li>Progress updates while images stream to browser storage</li>
												</ul>
										</div>
									</div>

									<div>
										<h3 class="text-foreground mb-4 font-semibold">Rarity Calculation System</h3>
										<p class="text-muted-foreground mb-4">
											Gallery Mode features six rarity calculation methods for comprehensive collection analysis.
										</p>

										<div class="grid grid-cols-1 gap-4 md:grid-cols-2 mb-4">
											<div class="border-border bg-muted rounded-lg border p-3">
												<h4 class="text-foreground mb-1 text-sm font-semibold">Trait Rarity</h4>
												<p class="text-muted-foreground text-xs">Sum of individual trait rarity scores based on frequency in the collection.</p>
											</div>
											<div class="border-border bg-muted rounded-lg border p-3">
												<h4 class="text-foreground mb-1 text-sm font-semibold">Average Trait Rarity</h4>
												<p class="text-muted-foreground text-xs">Mean of all trait rarity scores for balanced evaluation.</p>
											</div>
											<div class="border-border bg-muted rounded-lg border p-3">
												<h4 class="text-foreground mb-1 text-sm font-semibold">Weighted Trait Rarity</h4>
												<p class="text-muted-foreground text-xs">Later layers get higher weight for emphasis on foreground traits.</p>
											</div>
											<div class="border-border bg-muted rounded-lg border p-3">
												<h4 class="text-foreground mb-1 text-sm font-semibold">Standard Deviation</h4>
												<p class="text-muted-foreground text-xs">Statistical deviation from the mean for outlier detection.</p>
											</div>
											<div class="border-border bg-muted rounded-lg border p-3">
												<h4 class="text-foreground mb-1 text-sm font-semibold">Enhanced Weighted</h4>
												<p class="text-muted-foreground text-xs">Custom weights with tiered rarity system (Common → Legendary).</p>
											</div>
											<div class="border-border bg-muted rounded-lg border p-3">
												<h4 class="text-foreground mb-1 text-sm font-semibold">Emergent Rarity</h4>
												<p class="text-muted-foreground text-xs">Based on full trait combination uniqueness across the entire collection.</p>
											</div>
										</div>

										<div class="border-border bg-muted rounded-lg border p-4 mb-4">
											<h4 class="text-foreground mb-2 font-semibold">Trait Statistics & Analysis</h4>
											<ul class="text-muted-foreground ml-4 list-disc space-y-1 text-sm">
												<li><strong>Top 20 Rarest Traits:</strong> Ranked list with counts and percentages</li>
												<li><strong>Jaccard Similarity:</strong> Find items with similar trait combinations</li>
												<li><strong>Strategic Classification:</strong> Traits categorized as strategic, balanced, or filler</li>
												<li><strong>Rarity Tiers:</strong> Common, Uncommon, Rare, Epic, Legendary</li>
											</ul>
										</div>

										<div class="border-border bg-muted rounded-lg border p-4">
											<h4 class="text-foreground mb-2 font-semibold">How Rarity is Displayed</h4>
											<div class="grid grid-cols-1 gap-3 md:grid-cols-2">
												<div>
													<h5 class="text-foreground mb-1 text-sm font-medium">In Item Details Panel:</h5>
													<ul class="text-muted-foreground ml-4 list-disc space-y-1 text-xs">
														<li>Individual trait rarity percentages</li>
														<li>Overall item rarity score</li>
														<li>Global rarity rank (e.g., "Rank #42")</li>
													</ul>
												</div>
												<div>
													<h5 class="text-foreground mb-1 text-sm font-medium">In Collection Stats:</h5>
													<ul class="text-muted-foreground ml-4 list-disc space-y-1 text-xs">
														<li>Rarest item in the collection</li>
														<li>Average rarity score across all items</li>
														<li>Total number of unique traits</li>
													</ul>
												</div>
											</div>
										</div>
									</div>

									<div>
										<h3 class="text-foreground mb-4 font-semibold">Performance Features</h3>
										<div class="grid grid-cols-1 gap-4 md:grid-cols-2">
											<div>
												<h4 class="text-foreground mb-2 font-semibold">Caching & Storage</h4>
												<ul class="text-muted-foreground ml-4 list-disc space-y-1 text-sm">
													<li>Three-tier cache: ImageBitmap, ImageData, ArrayBuffer</li>
													<li>Filter result caching (LRU, max 50 entries)</li>
													<li>Streaming import with durable browser storage</li>
													<li>Storage quota monitoring with getStorageEstimate()</li>
												</ul>
											</div>
											<div>
													<h4 class="text-foreground mb-2 font-semibold">Sorting & Filtering</h4>
													<ul class="text-muted-foreground ml-4 list-disc space-y-1 text-sm">
														<li>Natural numeric sorting ("Foxinity #1", "#001")</li>
														<li>O(1) trait index lookups for instant filtering</li>
														<li>OR matching within a layer and AND matching across layers</li>
														<li>Reactive search through the gallery store</li>
													</ul>
												</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
