					<section class="animate-in fade-in duration-300">
						<div class="border-border bg-card rounded-lg border">
							<div class="border-border border-b px-6 py-4">
								<h2 class="text-foreground text-xl font-semibold">Technical Details</h2>
							</div>
							<div class="px-6 py-6">
								<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
									<div>
										<h3 class="text-foreground mb-3 font-semibold">Architecture</h3>
										<div class="text-foreground space-y-2 text-sm">
											<p>
												<strong class="text-foreground">Framework:</strong> SvelteKit 2 with Svelte 5 runes
											</p>
											<p>
												<strong class="text-foreground">Language:</strong> TypeScript with branded types
											</p>
											<p><strong class="text-foreground">Styling:</strong> Tailwind CSS 4 + NeoBr-UI</p>
											<p>
												<strong class="text-foreground">State:</strong> $state, $derived, $effect with auto-persistence
											</p>
											<p><strong class="text-foreground">Validation:</strong> Zod schemas with runtime type safety</p>
											<p><strong class="text-foreground">Deploy:</strong> Juno static hosting on ICP, PWA-ready</p>
										</div>
									</div>

									<div>
										<h3 class="text-foreground mb-3 font-semibold">Processing</h3>
										<div class="text-foreground space-y-2 text-sm">
											<p>
												<strong class="text-foreground">Engine:</strong> Canvas API + OffscreenCanvas in Web Workers
											</p>
											<p>
												<strong class="text-foreground">Worker Pool:</strong> Dynamic scaling (up to 8 workers) with health monitoring and work stealing
											</p>
											<p>
												<strong class="text-foreground">Solver:</strong> CSP with AC-3 arc consistency, MRV heuristic, weighted-random selection
											</p>
											<p>
												<strong class="text-foreground">Storage:</strong> OPFS-backed object storage with legacy fallback
											</p>
											<p>
												<strong class="text-foreground">Caching:</strong> Three-tier: ImageBitmap (100MB), ImageData (50MB), ArrayBuffer (200MB)
											</p>
										</div>
									</div>
								</div>

								<div class="bg-muted mt-6 rounded-lg p-4">
									<h4 class="text-foreground mb-2 font-semibold">Metadata Structure (ERC-721)</h4>
									<pre class="bg-card text-foreground overflow-x-auto rounded border p-3 text-xs">{`{
  "name": "Collection #1",
  "description": "Generated by GNStudio",
  "image": "images/1.png",
  "external_url": "...",
  "animation_url": "...",
  "youtube_url": "...",
  "background_color": "FFFFFF",
  "attributes": [
    {"trait_type": "Background", "value": "Blue"},
    {"trait_type": "Character", "value": "Robot"}
  ]
}`}</pre>
								</div>
								<div class="bg-muted mt-4 rounded-lg p-4">
									<h4 class="text-foreground mb-2 font-semibold">Metadata Structure (Solana/Metaplex)</h4>
									<pre class="bg-card text-foreground overflow-x-auto rounded border p-3 text-xs">{`{
  "name": "Collection #1",
  "symbol": "COL",
  "description": "Generated by GNStudio",
  "seller_fee_basis_points": 500,
  "image": "images/1.png",
  "external_url": "...",
  "attributes": [...],
  "collection": { "name": "...", "family": "..." },
  "properties": {
    "files": [{"uri": "images/1.png", "type": "image/png"}],
    "category": "image",
    "creators": [{"address": "...", "share": 100}]
  }
}`}</pre>
								</div>
							</div>
						</div>
					</section>
