name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ensure lockfile is up to date
        run: npm run verify-lockfile-ci

      - name: Run lint
        run: npm run lint-ci

      - name: Type check
        run: npm run check

      - name: Run tests
        run: npm run test:ci
